version: '2'
services:
    schoolar-app:
        image: schoolar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://schoolar-postgresql:5432/positivo-cloud
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    schoolar-postgresql:
        extends:
            file: postgresql.yml
            service: schoolar-postgresql
